### ISSUE TITLE
Organization "will be deleted" in the past

### ISSUE THREAD

**Issue by schambon** [ozwillo/ozwillo-portal#318]
Seen in dev environment: message "Will be deleted 4 hours ago" which is quite nonsensical.

Steps to reproduce: delete an organization then wait out the deletion timer.

![screenshot from 2015-11-13 16 14 57](https://cloud.githubusercontent.com/assets/2110554/11149254/dd7a07d6-8a21-11e5-82e4-e742ac7d07dd.png)

I haven't tried to reproduce in production so it could well be an artifact of the dev environment.

**Comment by tbroyer** [comment]
Cleanup on the Kernel side is (currently) done nightly (UTC), so this organization will only be deleted this night; the delay between "soft" and "hard" deletion is thus actually "between 7 and 8 days".

But even if we do clean more frequently that situation might still happen, so the Portal has to cope with it anyway (filter them out or display something different). Either that or the Kernel needs to actively filter out the organizations that _should have been hard-deleted already._

(and BTW, because it's now not that clear whether it should be seen as a Portal or Kernel issue, this is why we have an [ozwillo-issues project](https://github.com/ozwillo/ozwillo-issues/issues) ;-) )

**Comment by schambon** [comment]
Thanks for the heads-up about ozwillo-issues. Indeed it might be a better fit there. I wonder: is the deletion "deadline", so to speak, computed portal-side or kernel-side? If it's the kernel that decides when the org will be deleted, then that computation should align to the cleanup job. For instance if there's a 7-day waiting period then the deletion instant should be "the next time the cleanup job runs after 7 days have passed". That way the deletion delay as displayed by the portal is always correct and there is no extra work to do portal-side.

**Comment by tbroyer** [comment]
The deadline is not pre-computed, so that message in your screenshot is a Portal one, based on a delay that ought to be the same as the one on the Kernel side. When an organization will actually be deleted currently depends on a) when the cleanup job is run (it's currently scheduled nightly in the servers' crontab, but it could be run manually or rescheduled at different intervals, or fail to run for whatever reason) and b) what delay is configured in the cleanup job at the time it runs (so it can technically be changed, and all of a sudden organizations that would have been deleted in that run following a "7 days" delay might be kept longer, or organizations that would have been a few days later might be deleted in the current run).
But the Kernel doesn't communicate any deadline to the Portal.

Things can change, but first we need to know what we want, then specify how (best) to do it.

**Comment by mdutoo** [comment]
The existing code follows current specifications (in x days), constrained by moment.js abilities. So let's suggest the easiest solution (round to day, "planned deletion date: xxx", "should" instead of "will" which would also solve the case of old test orgs not been deleted in some envs...) after checking what can be easily done.
