### ISSUE TITLE
Enrich the "/status" controller

### ISSUE THREAD

**Issue by MLE-Astek** [ozwillo/ozwillo-portal#338]
It will be very useful to enrich the «/status» controller of the project, with the version and/or commit ID, etc.
For example we can generate this automatically with a maven plugin like [maven-git-commit-id-plugin](https://github.com/ktoso/maven-git-commit-id-plugin)

**Comment by tbroyer** [comment]
Beware that such information can mean exposing the fact that there's an exploitable vulnerability (e.g. if there's a commit fixing it that can thus easily be proved to not be deployed to that particular instance); that's security by obscurity (note that an attacker could just try known vulnerabilities that have been fixed recently, but there are vulnerabilities that can be fixed "implicitly", e.g. because you update a dependency or change some configuration)

IMO, if you want to know what runs on your server, you should either:
* automate the deployment so you only have to look at your CD pipeline (Puppet, whatever)
* log into the server and look wherever appropriate (for the Kernel for example I can do `dpkg -l oasis`, but that could also just be a file at a known location)

**Comment by MLE-Astek** [comment]
Well, of course we have to beware about public informations. But we have already a controller with the connection status of the database, we can put without risk the deployed version of the portal.
The deployment is not automatised, and verify the version on the server not ensure us that is this version running.

It's just a suggestion, not an obligation …
